window.musicAcademyData = {
    classes: [
        {
            id: "guitar-foundations",
            name: "Contemporary Guitar",
            category: "Strings",
            level: "Beginner",
            monthlyFee: 2400,
            duration: "60 min",
            schedule: "Tue / Thu 5:00 PM",
            batch: "Weekday",
            demoAvailable: true,
            ageGroup: "10+ years",
            icon: "🎸",
            blurb: "Rhythm patterns, fretboard basics, and performance-ready strumming drills.",
            instructor: "Arjun Menon"
        },
        {
            id: "piano-essentials",
            name: "Piano Essentials",
            category: "Keys",
            level: "Beginner",
            monthlyFee: 2800,
            duration: "60 min",
            schedule: "Mon / Wed 4:30 PM",
            batch: "Weekday",
            demoAvailable: true,
            ageGroup: "7+ years",
            icon: "🎹",
            blurb: "Keyboard orientation, notation reading, and simple repertoire building.",
            instructor: "Nisha Sethi"
        },
        {
            id: "violin-performance",
            name: "Violin Performance Lab",
            category: "Strings",
            level: "Intermediate",
            monthlyFee: 3200,
            duration: "75 min",
            schedule: "Sat 10:00 AM",
            batch: "Weekend",
            demoAvailable: true,
            ageGroup: "9+ years",
            icon: "🎻",
            blurb: "Bow control, tone production, and ensemble practice for progressing learners.",
            instructor: "Ritika Varma"
        },
        {
            id: "drums-rhythm-lab",
            name: "Drums Rhythm Lab",
            category: "Percussion",
            level: "Beginner",
            monthlyFee: 2600,
            duration: "60 min",
            schedule: "Fri 6:00 PM",
            batch: "Weekday",
            demoAvailable: true,
            ageGroup: "11+ years",
            icon: "🥁",
            blurb: "Stick control, groove fundamentals, timing work, and coordinated fills.",
            instructor: "Karan Bedi"
        },
        {
            id: "flute-expression",
            name: "Flute Expression",
            category: "Wind",
            level: "Intermediate",
            monthlyFee: 2200,
            duration: "50 min",
            schedule: "Sun 9:00 AM",
            batch: "Weekend",
            demoAvailable: true,
            ageGroup: "8+ years",
            icon: "🎶",
            blurb: "Breath control, tone shaping, and melody phrasing through guided pieces.",
            instructor: "Meera Kaul"
        },
        {
            id: "keyboard-production",
            name: "Keyboard and Harmony",
            category: "Keys",
            level: "Advanced",
            monthlyFee: 3400,
            duration: "90 min",
            schedule: "Sat / Sun 2:00 PM",
            batch: "Weekend",
            demoAvailable: false,
            ageGroup: "13+ years",
            icon: "🎛️",
            blurb: "Chord voicing, harmony drills, and arrangement skills for confident performers.",
            instructor: "Dev Malhotra"
        },
        {
            id: "vocals-stage-ready",
            name: "Vocals Stage Ready",
            category: "Vocals",
            level: "Beginner",
            monthlyFee: 1800,
            duration: "45 min",
            schedule: "Wed 6:30 PM",
            batch: "Weekday",
            demoAvailable: true,
            ageGroup: "12+ years",
            icon: "🎤",
            blurb: "Breathing, pitch stability, and confidence-building performance routines.",
            instructor: "Sara Joseph"
        }
    ]
};